version: v1
services:
  postgres:
    container_name: k8s-postgres
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - k8s-net

  zipkin:
    container_name: k8s-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - k8s-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: k8s-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - k8s-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: k8s-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://k8s-kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - k8s-net

  mail-dev:
    container_name: k8s-mail
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  portfolio:
    container_name: portfolio
    image: portfolio:dev
    ports:
      - "5173:5173"

networks:
  k8s-net:
    driver: bridge

volumes:
  postgres: