apiVersion: apps/v1
kind: Deployment
metadata:
  name: port
spec:
  replicas: 1
  template:
    metadata:
      name: port
      labels:
        app: port
    spec:
      containers:
       - name: port
         image: radiocat2000/portfolio:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 5173
      restartPolicy: Always
  selector:
    matchLabels:
      app: port

