apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  template:
    metadata:
      name: order
      labels:
        app: order
    spec:
      containers:
       - name: order
         image: radiocat2000/orderservicekb:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 8052
         env:
           - name: SPRING_PROFILES_ACTIVE
             value: kubernetes
      restartPolicy: Always
  selector:
    matchLabels:
      app: order

