apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      containers:
       - name: customer
         image: radiocat2000/customerservicekb:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 8050
         env:
           - name: SPRING_PROFILES_ACTIVE
             value: kubernetes
      restartPolicy: Always
  selector:
    matchLabels:
      app: customer

