apiVersion: v1
kind: Service
metadata:
  name: maildev
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 1080
      targetPort: 1080
    - name: smtp
      port: 1025
      targetPort: 1025
  selector:
    app: maildev